# Generated by Django 4.2.16 on 2024-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('ebook', 'E-book'), ('audiobook', 'Audiobook')], default='hardcover', max_length=12),
        ),
    ]
